### ISSUE TITLE
Indentación

### ISSUE THREAD

**Issue by DanBaDo** [LuisAguadoVicaria/react-todolist-fetch#1]
Dolor.

Es *imprescindible* que la indentación sea adecuada.

https://github.com/LuisAguadoVicaria/react-todolist-fetch/blob/069f2d9e779b97c8d2c690380776cf7142787d6c/src/App.js#L9-L14

**Comment by LuisAguadoVicaria** [comment]
Fix:

#https://github.com/LuisAguadoVicaria/react-todolist-fetch/commit/5121b923a82693040b2b8f4afb454799a4aa5add
